sudo: false

language: python

dist: xenial

addons:
  apt:
    packages:
      - expect-dev

python:
  - "3.6"
  - "3.8"

cache: pip

install:
  - pip install six     # Using six dependency for text_type()
  - pip install joblib  # For parallelization.
  - pip install click   # For CLI.
  - pip install tqdm    # For progressbar.
  - pip install regex   # For regex (simpler access to perluniprops)

script:
  - unbuffer python -m unittest discover sacremoses/test/ -v
